spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  host: https://refile.herokuapp.com
  front-end: http://localhost:3000

server:
  servlet:
    session:
      cookie:
        same-site: "none"
